src/blog/urls.py
from django.urls import path


from . import views


app_name = "blog"


urlpatterns = [
    path("posts/", views.post_list_view, name="post_list"),
    path(
        "posts/tag/<slug:tag_slug>/", views.post_list_view, name="post_list_by_tag"
    ),  # list posts by tags
    path(
        "posts/<int:year>/<int:month>/<int:day>/<int:hour>/<int:minute>/<int:second>/<slug:slug>/",
        views.post_detail_view,
        name="post_detail",
    ),
    path("posts/<int:id>/share/", views.post_share_view, name="post_share"),
    path(
        "posts/<int:post_id>/comment/add/",
        views.add_post_comment_view,
        name="add_post_comment",
    ),
    path("posts/search/", views.post_search_view, name="post_search"),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    "posts": PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

src/blog/models.py
from taggit.managers import TaggableManager

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone



class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="posts", on_delete=models.CASCADE
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True, unique_for_date="publish_at")
    body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_published = models.BooleanField(default=False)
    publish_at = models.DateTimeField(default=timezone.now)
    # image = models.ImageField(upload_to='posts')

    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )
    
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish_at"]
        indexes = [
            models.Index(fields=["-publish_at"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return reverse(
            "blog:post_detail",
            kwargs={
                "slug": self.slug,
                
                "year": self.publish_at.year,
                "month": self.publish_at.month,
                "day": self.publish_at.day,
                
                "hour": self.publish_at.hour,
                "minute": self.publish_at.minute,
                "second": self.publish_at.second,
            },
        )

class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name="comments", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    active = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_at"]
        
    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post.title}'

src/blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        
class SearchForm(forms.Form):
    query = forms.CharField()

src/blog/views.py
from taggit.models import Tag

from django.shortcuts import get_object_or_404, redirect, render

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.db.models import Prefetch
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from .models import Comment, Post
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list_view(request, tag_slug=None):
    post_qs = Post.objects.filter(status=Post.Status.PUBLISHED)

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_qs = post_qs.filter(tags__in=[tag])

    posts_per_page = 3
    paginator = Paginator(post_qs, posts_per_page)
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {"posts": posts, "tag": tag}
    return render(request, "blog/post/list.html", context)


def post_detail_view(request, year, month, day, hour, second, minute, slug):
    post = get_object_or_404(
        Post.objects.prefetch_related(
            Prefetch("comments", queryset=Comment.objects.filter(active=True))
        ),
        status=Post.Status.PUBLISHED,
        slug=slug,
        publish_at__year=year,
        publish_at__month=month,
        publish_at__day=day,
        publish_at__hour=hour,
        publish_at__minute=minute,
        publish_at__second=second,
    )

    # list similar posts
    post_tags_ids = post.tags.values_list("id", flat=True)  # get tags IDs for each post
    similar_posts = Post.objects.filter(
        tags__in=post_tags_ids, status=Post.Status.PUBLISHED
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish_at"
    )  # sort similar posts by the number of tags

    # display add comment form
    comment_form = CommentForm()

    context = {
        "post": post,
        "comment_form": comment_form,
        "similar_posts": similar_posts,
    }

    return render(request, "blog/post/detail.html", context)


def post_share_view(request, id):
    """
    Share post --> send it by Email
    """
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        id=id,
    )
    form = EmailPostForm()
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            clean_date = form.cleaned_data

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{clean_date['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n{clean_date['name']}'s comments: {clean_date['comments']}"

            send_mail(
                subject,
                message,
                "elbalky4@gmail.com",
                [clean_date["to"]],
                fail_silently=False,
            )
            sent = True
    context = {"form": form, "sent": sent, "post": post}
    return render(request, "blog/post/share.html", context)


@require_POST
def add_post_comment_view(request, post_id):
    """
    Comment on a post
    """
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        id=post_id,
    )

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post.get_absolute_url())


def post_search_view(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            
            search_vector = SearchVector("title", "body")
            search_query = SearchQuery(query, config="english")
            
            results = (
                Post.objects.annotate(
                    search=search_vector,
                    rank=SearchRank(search_vector, search_query),
                )
                .filter(search=search_query, status=Post.Status.PUBLISHED)
                .order_by("-rank")
            )

    context = {"form": form, "query": query, "results": results}
    return render(request, "blog/post/search.html", context)

src/blog/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>

<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog.</p>
        <p><a href="{% url 'blog:post_list' %}">Posts list ({% total_posts %} posts)</a></p>
        <div>
            <h3>Show latest posts:</h3>
            {% show_latest_posts 3 %}
        </div>
        <div>
            <h3>Most Commented posts:</h3>
            <ul>
                {% get_most_commented_posts 2 as most_commented_posts %}
                {% for post in most_commented_posts %}
                <li style="margin-bottom: 5px;">
                    <a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }} ({{ post.total_commented }} comments)</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>

</html>

src/blog/templates/blog/comment/form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:add_post_comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Add comment"></p>
</form>

src/blog/templates/blog/comment/list.html
{% with post.comments.count as total_comments %}
<h2 style="padding-bottom: 10px;">
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in post.comments.all %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks|truncatewords:20}}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

src/blog/templates/blog/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
    Published at {{ post.publish_at }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }} - {{ post.same_tags }}</a>
        </p>
    {% empty %}
    There are no similar posts yet...
    {% endfor %}
    
    {% include "blog/comment/list.html" with post=post %}
    {% include "blog/comment/form.html" with form=comment_form %}

{% endblock %}

src/blog/templates/blog/post/latest_psots.html
<ul>
    {% for post in latest_posts %}
    <li style="margin-bottom: 5px;">
        <a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
    </li>
    {% endfor %}
</ul>

src/blog/templates/blog/post/list.html
{% extends "base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

<h1>My Blog</h1>

{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title|capfirst }}
    </a>
</h2>

<p class="tags">Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_by_tag' tag_slug=tag.slug %}">
        {{ tag.name|capfirst }}
    </a>
    {% if not forloop.last %}
    ,
    {% endif %}
    {% endfor %}
</p>

<p class="date">
    Published at {{ post.publish_at|date:"Y-m-d, h:i A" }} by {{ post.author }}
</p>
{{ post.body|capfirst|truncatewords:30|linebreaks }}
<hr />
{% endfor %}

{% include 'pagination.html' with page=posts %}

{% endblock %}

src/blog/templates/blog/post/search.html
{% extends 'base.html' %}

{% block title %}
Search
{% endblock title %}

{% block content %}
{% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </h3>

    {% for post in results %}
        <div class="comment">
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|truncatewords_html:12 }}
        </div>
    {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}

    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>

{% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
{% endif %}
{% endblock %}

src/blog/templates/blog/post/share.html
{% extends "base.html" %}

{% block title %}Share a Post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
        <br>
        <p>
            <a href="{% url 'blog:post_list' %}">Back to posts list</a>
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

src/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>